services:
  nats:
    image: nats:2.10.24-alpine
    container_name: nats-server
    ports:
      - '4222:4222'
      - '8222:8222'
    command: ['-p', '4222', '-m', '8222', '-D']
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:8222/healthz']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
